const PATHS={
    home:{
        path:`/home`,
        template:``
    },
    regEmployee:{
        path:`/registEmployee`,
        template:``
    },
    employeeList:{
        path:`/employeeList`,
        template:``
    },
    regClient:
    {
        path:`/registClient`,
        template:``
    },
    clientList:
    {
        path:`/client`,
        template:``
    },
    report:
    {
        path:`/report`,
        template:``
    }
}